<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PDQBIIN" failures="2" tests="3" name="Test" time="13.238" errors="0" timestamp="2025-01-02T15:32:32 SEÄŒ">
  <testcase classname="com.parabank.parasoft.testCases.LoginTest" name="TC_01_loginWithValidCredentials" time="0.962"/>
  <testcase classname="com.parabank.parasoft.testCases.LoginTest" name="TC_02_loginUserWithInvalidUsername" time="0.927">
    <failure type="java.lang.AssertionError" message="Account login with invalid username should fail, but it succeeded expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Account login with invalid username should fail, but it succeeded expected [false] but found [true]
at com.parabank.parasoft.testCases.LoginTest.TC_02_loginUserWithInvalidUsername(LoginTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC_02_loginUserWithInvalidUsername -->
  <testcase classname="com.parabank.parasoft.testCases.LoginTest" name="TC_03_loginUserWithInvalidPassword" time="1.561">
    <failure type="java.lang.AssertionError" message="Account login with invalid password should fail, but it succeeded expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Account login with invalid password should fail, but it succeeded expected [false] but found [true]
at com.parabank.parasoft.testCases.LoginTest.TC_03_loginUserWithInvalidPassword(LoginTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC_03_loginUserWithInvalidPassword -->
</testsuite> <!-- Test -->
